# The URL the site will be built for
base_url = "https://zola-themes.github.io/evening"

compile_sass = true
title = "Evening theme"
description = ""
generate_feed = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
author = "Zola Themes"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

even_title = "Evening"
